# Generated by Django 3.1.5 on 2021-10-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='hide_email',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_accepted',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_customer',
        ),
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.IntegerField(choices=[(0, 'محاسب'), (1, 'مندوب'), (2, 'عميل'), (3, 'محصل'), (4, 'محول'), (5, 'مدير')], default=0, verbose_name='نوع الحساب'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='نشط'),
        ),
    ]
