# Generated by Django 3.1.5 on 2021-12-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20211016_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_no',
            field=models.IntegerField(blank=True, help_text='مطلوب إضافة رقم الحساب', null=True, verbose_name='الرقم الكودى'),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(help_text='مطلوب إضافة الايميل', max_length=60, null=True, verbose_name='الإيميل'),
        ),
    ]
