# Generated by Django 3.1.5 on 2022-01-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20211219_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_open',
            field=models.BooleanField(default=False, verbose_name='متاح'),
        ),
    ]
