# Generated by Django 3.1.5 on 2021-07-10 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vono', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='areaName',
            new_name='area_name',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='branchName',
            new_name='branch_name',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='districtName',
            new_name='district_name',
        ),
        migrations.RenameField(
            model_name='ror',
            old_name='dateOfRecord',
            new_name='date_record',
        ),
        migrations.RenameField(
            model_name='vodafonenumber',
            old_name='dateOfRecord',
            new_name='date_record',
        ),
    ]
