# Generated by Django 3.1.5 on 2021-10-28 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=50, verbose_name='إسم المنطقة')),
                ('selected', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'المنطقة',
                'verbose_name_plural': 'المناطق',
                'db_table': 'Area',
                'ordering': ['-area_name'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=50, verbose_name='إسم الفرع')),
                ('selected', models.BooleanField(default=False)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vonoApp.area', verbose_name='المنطقة')),
            ],
            options={
                'verbose_name': 'الفرع',
                'verbose_name_plural': 'الفرع',
                'db_table': 'Branch',
                'ordering': ['-branch_name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=50, verbose_name='إسم القطاع')),
                ('selected', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'القطاع',
                'verbose_name_plural': 'القطاعات',
                'db_table': 'District',
                'ordering': ['-district_name'],
            },
        ),
        migrations.CreateModel(
            name='ROR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_record', models.DateField(auto_now=True, verbose_name='تاريخ التسجيل')),
            ],
        ),
        migrations.CreateModel(
            name='VodafoneNumberShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15, null=True, verbose_name='رقم التليفون')),
                ('area', models.CharField(max_length=50, null=True, verbose_name='المنطقة')),
                ('branch', models.CharField(max_length=50, null=True, verbose_name='الفرع')),
                ('best', models.IntegerField(default=0, null=True, verbose_name='الأفضل')),
                ('reviewer', models.CharField(max_length=50, null=True, verbose_name='المراجع')),
                ('version', models.DateField(null=True, verbose_name='اخر إصدار')),
                ('date_record', models.DateField(auto_now=True, null=True, verbose_name='تاريخ إصداره')),
                ('deleted', models.BooleanField(default=False, null=True, verbose_name='تم مسحه؟')),
            ],
            options={
                'verbose_name': 'عرض رقم فودافون ',
                'verbose_name_plural': ' عرض أرقام فودافون',
                'db_table': 'VodafoneNumberShow',
                'ordering': ['-area'],
            },
        ),
        migrations.CreateModel(
            name='VodafoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15, null=True, verbose_name='رقم التليفون')),
                ('best', models.IntegerField(default=0, null=True, verbose_name='الأفضل')),
                ('version', models.DateField(null=True, verbose_name='اخر إصدار')),
                ('date_record', models.DateField(auto_now=True, null=True, verbose_name='تاريخ إصداره')),
                ('is_deleted', models.BooleanField(default=False, null=True, verbose_name='تم مسحه')),
                ('is_available', models.BooleanField(default=False, null=True, verbose_name='متاح للعرض')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vonoApp.area', verbose_name='المنطقة')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vonoApp.branch', verbose_name='الفرع')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='VodafoneNumber.user+', to=settings.AUTH_USER_MODEL, verbose_name='تابع لحساب')),
            ],
            options={
                'verbose_name': 'رقم فودافون',
                'verbose_name_plural': 'أرقام فودافون',
                'db_table': 'VodafoneNumber',
                'ordering': ['-area'],
            },
        ),
        migrations.AddField(
            model_name='area',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vonoApp.district', verbose_name='القطاع'),
        ),
    ]
