# Generated by Django 3.1.5 on 2021-09-27 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=50, verbose_name='إسم المنطقة')),
                ('selected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=50, verbose_name='إسم القطاع')),
                ('selected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ROR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_record', models.DateField(auto_now=True, verbose_name='تاريخ التسجيل')),
            ],
        ),
        migrations.CreateModel(
            name='VodafoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15, null=True, verbose_name='رقم التليفون')),
                ('area', models.CharField(max_length=50, null=True, verbose_name='المنطقة')),
                ('branch', models.CharField(max_length=50, null=True, verbose_name='الفرع')),
                ('best', models.IntegerField(default=0, null=True, verbose_name='الأفضل')),
                ('reviewer', models.CharField(max_length=50, null=True, verbose_name='المراجع')),
                ('version', models.DateField(null=True, verbose_name='اخر إصدار')),
                ('date_record', models.DateField(auto_now=True, null=True, verbose_name='تاريخ إصداره')),
                ('deleted', models.BooleanField(default=False, null=True, verbose_name='تم مسحه؟')),
            ],
            options={
                'verbose_name': 'رقم فودافون',
                'verbose_name_plural': 'أرقام فودافون',
                'ordering': ['-area'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=50, verbose_name='إسم الفرع')),
                ('selected', models.BooleanField(default=False)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vonoApp.area', verbose_name='المنطقة')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vonoApp.district', verbose_name='القطاع'),
        ),
    ]
