# Generated by Django 3.1.5 on 2021-08-30 01:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest', models.FloatField(blank=True, null=True, verbose_name='المتبقى')),
                ('date', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Date')),
                ('time', models.TimeField(default=django.utils.timezone.now, null=True, verbose_name='Time')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='customers.customerinfo', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'المتبقى',
                'verbose_name_plural': 'المتبقيات',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('فورى', 'فورى'), ('كاش', 'كاش'), ('طاير', 'طاير'), ('بى', 'بى'), ('أمان', 'أمان'), ('أخرى', 'أخرى'), ('تنزيل', 'تنزيل')], default=1, max_length=50, verbose_name='نوع الحساب')),
                ('value', models.FloatField(verbose_name='المبلغ')),
                ('isDone', models.BooleanField(blank=True, null=True, verbose_name='انتهاء السداد')),
                ('isDown', models.BooleanField(blank=True, null=True, verbose_name='تحويل أم تنزبل')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('time', models.TimeField(default=django.utils.timezone.now, verbose_name='Time')),
                ('customerData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customerData', to='customers.customerinfo', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'تحويل',
                'verbose_name_plural': 'سجل التحويلات',
                'managed': True,
            },
        ),
    ]
