# Generated by Django 3.1.5 on 2021-10-22 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0006_auto_20211022_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talabat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.IntegerField(choices=[(1, 'عميل'), (2, 'مندوب'), (3, 'محصل'), (4, 'مشرف')], default=1, verbose_name='المرسل')),
                ('type', models.CharField(choices=[('فورى', 'فورى'), ('كاش', 'كاش'), ('طاير', 'طاير'), ('بى', 'بى'), ('أمان', 'أمان'), ('أخرى', 'أخرى'), ('تنزيل', 'تنزيل')], default=1, max_length=50, verbose_name='نوع الحساب')),
                ('value', models.FloatField(verbose_name='المبلغ')),
                ('periority', models.IntegerField(blank=True, choices=[(1, 'عادى'), (2, 'مستعجل'), (3, 'مستعجل جداً'), (4, 'مستعجل للغاية')], default=1, null=True, verbose_name='الاولوية')),
                ('stateTrans', models.IntegerField(blank=True, choices=[(1, 'تم الطلب'), (2, 'جارى تنفيذ الطلب'), (3, 'طلب ناجح'), (4, 'طلب فاشل'), (5, 'طلب موفوف'), (6, 'طلب معطل'), (7, 'طلب مسحوب')], default=1, null=True, verbose_name='حالة الطلب')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('time', models.TimeField(default=django.utils.timezone.now, verbose_name='Time')),
                ('dateTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Time')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Talabat.account+', to=settings.AUTH_USER_MODEL, verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'طلب',
                'verbose_name_plural': 'سجل الطلبات',
                'ordering': ['-dateTime'],
            },
        ),
        migrations.CreateModel(
            name='Rest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, null=True, verbose_name='المتبقى')),
                ('date', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Date')),
                ('time', models.TimeField(default=django.utils.timezone.now, null=True, verbose_name='Time')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Rest.customer+', to='customers.customerinfo', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'المتبقى',
                'verbose_name_plural': 'المتبقيات',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('فورى', 'فورى'), ('كاش', 'كاش'), ('طاير', 'طاير'), ('بى', 'بى'), ('أمان', 'أمان'), ('أخرى', 'أخرى'), ('تنزيل', 'تنزيل')], default=1, max_length=50, verbose_name='نوع الحساب')),
                ('value', models.FloatField(verbose_name='المبلغ')),
                ('isDone', models.BooleanField(blank=True, null=True, verbose_name='انتهاء السداد')),
                ('isDown', models.BooleanField(blank=True, null=True, verbose_name='تحويل أم تنزبل')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('time', models.TimeField(default=django.utils.timezone.now, verbose_name='Time')),
                ('notes', models.TextField(blank=True, max_length=150, null=True, verbose_name='الملاحظات')),
                ('accountant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accountant', to=settings.AUTH_USER_MODEL, verbose_name='المحاسب')),
                ('customerData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customerData', to='customers.customerinfo', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'تحويل',
                'verbose_name_plural': 'سجل التحويلات',
                'managed': True,
            },
        ),
    ]
