# Generated by Django 3.1.5 on 2021-09-04 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rest',
            old_name='rest',
            new_name='value',
        ),
        migrations.AlterModelTable(
            name='record',
            table='record',
        ),
        migrations.AlterModelTable(
            name='rest',
            table='rest',
        ),
    ]
