# Generated by Django 3.1.5 on 2021-09-27 14:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20210918_1407'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rest',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Rest.customer+', to='customers.customerinfo', verbose_name='العميل'),
        ),
        migrations.CreateModel(
            name='Talabat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('عميل', 'عميل'), ('مندوب', 'مندوب'), ('محصل', 'محصل')], default=1, max_length=50, verbose_name='المرسل')),
                ('type', models.CharField(choices=[('فورى', 'فورى'), ('كاش', 'كاش'), ('طاير', 'طاير'), ('بى', 'بى'), ('أمان', 'أمان'), ('أخرى', 'أخرى'), ('تنزيل', 'تنزيل')], default=1, max_length=50, verbose_name='نوع الحساب')),
                ('value', models.FloatField(verbose_name='المبلغ')),
                ('isDown', models.BooleanField(blank=True, null=True, verbose_name='تحويل أم تنزبل')),
                ('periority', models.IntegerField(blank=True, choices=[(1, 'عادى'), (2, 'مستعجل'), (3, 'مستعجل جداً'), (4, 'مستعجل للغاية')], default=1, null=True, verbose_name='الاولوية')),
                ('stateTrans', models.IntegerField(blank=True, choices=[(1, 'تم الطلب'), (2, 'جارى تنفيذ الطلب'), (3, 'طلب ناجح'), (4, 'طلب فاشل'), (5, 'طلب موفوف'), (6, 'طلب معطل')], default=1, null=True, verbose_name='حالة الطلب')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('time', models.TimeField(default=django.utils.timezone.now, verbose_name='Time')),
                ('dateTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Time')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Talabat.customer+', to='customers.customerinfo', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'تحويل',
                'verbose_name_plural': 'سجل التحويلات',
                'ordering': ['-dateTime'],
            },
        ),
    ]
