# Generated by Django 3.1.5 on 2021-09-04 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20210904_1223'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='record',
            table=None,
        ),
        migrations.AlterModelTable(
            name='rest',
            table=None,
        ),
    ]
