# Generated by Django 3.1.5 on 2021-10-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20211002_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='notes',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='الملاحظات'),
        ),
    ]
