# Generated by Django 3.1.5 on 2021-10-22 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_auto_20211022_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rest',
            old_name='rest',
            new_name='value',
        ),
    ]
