# Generated by Django 3.1.5 on 2021-10-23 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0008_auto_20211022_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talabat',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Talabat.account+', to=settings.AUTH_USER_MODEL, verbose_name='العميل'),
        ),
    ]
