# Generated by Django 3.1.5 on 2021-10-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_auto_20211026_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rest',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'متبقيات'), (2, 'مدفوعات')], default=1, null=True, verbose_name=' النوع '),
        ),
    ]
