# Generated by Django 3.1.5 on 2021-10-26 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_auto_20211026_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rest',
            name='type',
        ),
    ]
