# Generated by Django 3.1.5 on 2021-10-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_remove_rest_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rest',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'متبقيات'), (2, 'مدفوعات')], default=1, null=True, verbose_name=' النوع '),
        ),
        migrations.AlterField(
            model_name='record',
            name='rest',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='المتبقى'),
        ),
    ]
