# Generated by Django 3.1.5 on 2021-10-30 17:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_auto_20211026_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='DateTime'),
        ),
    ]
