# Generated by Django 3.1.5 on 2021-10-30 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_record_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='DateTime'),
        ),
    ]
