# Generated by Django 3.1.5 on 2021-10-31 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_auto_20211030_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='isDone',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='انتهاء السداد'),
        ),
        migrations.AlterField(
            model_name='record',
            name='isDown',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='تحويل أم تنزبل'),
        ),
    ]
