# Generated by Django 3.1.5 on 2021-12-13 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0019_auto_20211213_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logdate',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='DateTime'),
        ),
    ]
