# Generated by Django 3.1.5 on 2021-12-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0021_auto_20211213_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='logdate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='logdate',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
