# Generated by Django 3.1.5 on 2021-12-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0022_auto_20211213_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logdate',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='logdate',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
