# Generated by Django 3.1.5 on 2021-12-25 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0023_auto_20211213_1147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'managed': True, 'ordering': ['-datetime'], 'verbose_name': 'تحويل', 'verbose_name_plural': 'سجل التحويلات'},
        ),
    ]
