# Generated by Django 3.1.5 on 2021-12-25 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0024_auto_20211225_1344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'managed': True, 'verbose_name': 'تحويل', 'verbose_name_plural': 'سجل التحويلات'},
        ),
    ]
