# Generated by Django 3.1.5 on 2021-12-07 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shakawa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.IntegerField(blank=True, choices=[(0, 'عام'), (1, 'مكن'), (2, 'تحويل'), (3, 'كاش'), (4, 'فورى'), (5, 'أمان')], default=1, null=True, verbose_name='نوع المشكلة')),
                ('content', models.TextField(verbose_name='المشكلة')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('time', models.TimeField(default=django.utils.timezone.now, verbose_name='Time')),
                ('dateTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Time')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Shakawa.account+', to=settings.AUTH_USER_MODEL, verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'شكوى',
                'verbose_name_plural': 'سجل الشكاوى',
                'ordering': ['-dateTime'],
            },
        ),
    ]
