# Generated by Django 3.1.5 on 2021-12-07 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shakawaApp', '0003_auto_20211207_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shakawa',
            name='dateTime',
            field=models.DateTimeField(blank=True, default=datetime.date.today, verbose_name='Date Time'),
        ),
    ]
