# Generated by Django 3.1.5 on 2021-12-07 13:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shakawaApp', '0006_auto_20211207_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shakawa',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='shakawa',
            name='dateTime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date Time'),
        ),
        migrations.AlterField(
            model_name='shakawa',
            name='time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Time'),
        ),
    ]
