# Generated by Django 3.1.5 on 2021-01-15 12:37

from django.db import migrations, models
import django.utils.timezone
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الإســم')),
                ('idNo', models.CharField(max_length=11, null=True, verbose_name='الرقم القومى')),
                ('shopName', models.CharField(max_length=45, null=True, verbose_name='إسم المحل')),
                ('shopKind', models.CharField(choices=[('بقالة', 'بقالة'), ('منظفات', 'منظفات'), ('سنترال', 'سنترال'), ('صيانة محمول', 'صيانة محمول'), ('إكسسوارات محمول', 'إكسسوارات محمول'), ('أدوات صحية', 'أدوات صحية'), ('مكتبة', 'مكتبة'), ('شخصى', 'شخصى')], max_length=50, null=True, verbose_name='نوع المحل')),
                ('phoneNo', phone_field.models.PhoneField(blank=True, help_text='قم بكتابة رقم التليفون ', max_length=31, verbose_name='رقم التليفون')),
                ('address', models.TextField(max_length=150, null=True, verbose_name='العنوان')),
                ('date', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Date')),
                ('time', models.TimeField(default=django.utils.timezone.now, null=True, verbose_name='Time')),
            ],
        ),
    ]
