# Generated by Django 3.1.5 on 2021-09-06 12:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MandopInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(blank=True, null=True, verbose_name='الرقم الكودى')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإيميل')),
                ('name', models.CharField(max_length=100, verbose_name='إسم المندوب')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='رقم التليفون')),
                ('region', models.CharField(blank=True, max_length=50, null=True, verbose_name='المنطقة')),
                ('date', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Date')),
                ('time', models.TimeField(default=django.utils.timezone.now, null=True, verbose_name='Time')),
            ],
            options={
                'verbose_name': 'بيانات المندوب',
                'verbose_name_plural': 'بيانات المناديب',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الإســم')),
                ('surName', models.CharField(blank=True, max_length=50, null=True, verbose_name=' إسم الشهره')),
                ('shopName', models.CharField(max_length=45, null=True, verbose_name='إسم المحل')),
                ('deviceNo', models.IntegerField(blank=True, null=True, unique=True, verbose_name='الرقم الكودى')),
                ('shopKind', models.CharField(choices=[('بقالة', 'بقالة'), ('منظفات', 'منظفات'), ('سنترال', 'سنترال'), ('صيانة محمول', 'صيانة محمول'), ('إكسسوارات محمول', 'إكسسوارات محمول'), ('أدوات صحية', 'أدوات صحية'), ('مكتبة', 'مكتبة'), ('شخصى', 'شخصى')], default=1, max_length=50, null=True, verbose_name='نوع المحل')),
                ('phoneNo', models.CharField(blank=True, help_text='قم بكتابة رقم التليفون ', max_length=11, verbose_name='رقم التليفون')),
                ('address', models.TextField(blank=True, max_length=150, null=True, verbose_name='العنوان')),
                ('area', models.CharField(max_length=50, null=True, verbose_name='المنطقة')),
                ('accounts', models.TextField(blank=True, default='', null=True, verbose_name='حسابات العميل')),
                ('date', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Date')),
                ('time', models.TimeField(default=django.utils.timezone.now, null=True, verbose_name='Time')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seller', to='customers.mandopinfo', verbose_name='المندوب المسئول')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
            ],
            options={
                'verbose_name': 'إضافة عميل',
                'verbose_name_plural': 'قائمة العملاء',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('customers.customerinfo',),
        ),
    ]
