# Generated by Django 3.1.5 on 2021-09-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='shopName',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='إسم المحل'),
        ),
    ]
