# Generated by Django 3.1.5 on 2021-01-15 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(null=True, upload_to='arshiv/Customerimages', verbose_name='وجه البطاقة')),
                ('image2', models.ImageField(null=True, upload_to='arshiv/Customerimages', verbose_name='ظهر البطاقة')),
                ('image3', models.ImageField(null=True, upload_to='arshiv/Customerimages', verbose_name='صورة مستند')),
            ],
        ),
        migrations.AddField(
            model_name='customer_info',
            name='images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer_image', verbose_name='المستندات'),
        ),
    ]
