# Generated by Django 3.1.5 on 2021-09-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='area',
            field=models.CharField(max_length=50, null=True, verbose_name='المنطقة'),
        ),
    ]
