# Generated by Django 3.1.5 on 2021-09-04 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customerinfo_area'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customerinfo',
            table='customerInfo',
        ),
        migrations.AlterModelTable(
            name='mandopinfo',
            table='mandopInfo',
        ),
    ]
