# Generated by Django 3.1.5 on 2021-01-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20210115_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_info',
            name='shopKind',
            field=models.CharField(choices=[('بقالة', 'بقالة'), ('منظفات', 'منظفات'), ('سنترال', 'سنترال'), ('صيانة محمول', 'صيانة محمول'), ('إكسسوارات محمول', 'إكسسوارات محمول'), ('أدوات صحية', 'أدوات صحية'), ('مكتبة', 'مكتبة'), ('شخصى', 'شخصى')], default=1, max_length=50, null=True, verbose_name='نوع المحل'),
        ),
    ]
