# Generated by Django 3.1.5 on 2021-09-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20210913_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='الإســم'),
        ),
        migrations.AlterField(
            model_name='mandopinfo',
            name='code',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='الرقم الكودى'),
        ),
        migrations.AlterField(
            model_name='mandopinfo',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='الإيميل'),
        ),
        migrations.AlterField(
            model_name='mandopinfo',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='إسم المندوب'),
        ),
    ]
