# Generated by Django 3.1.5 on 2021-09-04 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20210904_1223'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customerinfo',
            table=None,
        ),
        migrations.AlterModelTable(
            name='mandopinfo',
            table=None,
        ),
    ]
