# Generated by Django 3.1.5 on 2021-10-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20210918_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='notes',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='الملاحظات'),
        ),
    ]
