# Generated by Django 3.1.5 on 2021-01-17 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_article_comment_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
            ],
            options={
                'verbose_name': 'إضافة عميل',
                'verbose_name_plural': 'قائمة العملاء',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('customers.customer_info',),
        ),
        migrations.RemoveField(
            model_name='customer_info',
            name='images',
        ),
    ]
