# Generated by Django 3.1.5 on 2021-10-21 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0004_customerinfo_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='accountant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CustomerInfo.accountant+', to=settings.AUTH_USER_MODEL, verbose_name='تابع لحساب'),
        ),
    ]
