# Generated by Django 3.1.5 on 2021-01-17 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20210117_0346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer_info',
            options={'verbose_name': 'عميل', 'verbose_name_plural': 'العملاء'},
        ),
        migrations.AddField(
            model_name='customer_info',
            name='images',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer_image', verbose_name='المستندات'),
        ),
    ]
