# Generated by Django 3.1.5 on 2021-12-10 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_auto_20211022_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='إسم المنطقة')),
            ],
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='areas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CustomerInfo.areas+', to='customers.areas', verbose_name='إسم المنطقة'),
        ),
        migrations.AddField(
            model_name='mandopinfo',
            name='areas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='MandopInfo.areas+', to='customers.areas', verbose_name='إسم المنطقة'),
        ),
    ]
