# Generated by Django 3.1.5 on 2021-01-17 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_auto_20210117_0439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الإســم')),
                ('idNo', models.CharField(max_length=11, null=True, verbose_name='العنوان')),
            ],
            options={
                'verbose_name': 'حساب العميل',
                'verbose_name_plural': 'حساب العملاء',
            },
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.AddField(
            model_name='customer_info',
            name='account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer_account', verbose_name='حساب العميل'),
        ),
    ]
