# Generated by Django 3.1.5 on 2021-12-10 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_auto_20211210_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areas',
            options={'managed': True, 'verbose_name': 'المنطقة', 'verbose_name_plural': 'المناطق'},
        ),
    ]
