# Generated by Django 3.1.5 on 2021-07-04 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_auto_20210117_0448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer_account',
            options={'managed': True, 'verbose_name': 'حساب العميل', 'verbose_name_plural': 'حساب العملاء'},
        ),
        migrations.AlterModelOptions(
            name='customer_image',
            options={'managed': True, 'verbose_name': 'صور عميل', 'verbose_name_plural': 'أرشيف صور العملاء'},
        ),
        migrations.AlterModelOptions(
            name='customer_info',
            options={'managed': True, 'verbose_name': 'عميل', 'verbose_name_plural': 'العملاء'},
        ),
        migrations.AlterModelTable(
            name='customer_account',
            table='customers_customer_account',
        ),
        migrations.AlterModelTable(
            name='customer_image',
            table='customers_customer_image',
        ),
        migrations.AlterModelTable(
            name='customer_info',
            table='customers_customer_info',
        ),
    ]
