# Generated by Django 3.1.5 on 2021-12-12 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_auto_20211210_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assistant', to='customers.mandopinfo', verbose_name='المندوب الإحطياطى'),
        ),
    ]
