# Generated by Django 3.1.5 on 2021-12-15 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0009_customerinfo_assistant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CustomerInfo.user+', to=settings.AUTH_USER_MODEL, verbose_name='تابع لحساب'),
        ),
    ]
