# Generated by Django 3.1.5 on 2021-12-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_auto_20211215_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areas',
            options={},
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='accounts_data',
            field=models.TextField(blank=True, default='', null=True, verbose_name='سجل حسابات العميل'),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='grade',
            field=models.IntegerField(blank=True, null=True, verbose_name='الدرجة'),
        ),
    ]
