# Generated by Django 3.1.5 on 2022-03-30 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_auto_20220330_1438'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customerinfo',
            table=None,
        ),
        migrations.AlterModelTable(
            name='mandopinfo',
            table=None,
        ),
    ]
