# Generated by Django 3.1.5 on 2021-09-27 14:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_auto_20210918_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('فورى', 'فورى'), ('كاش', 'كاش'), ('طاير', 'طاير'), ('بى', 'بى'), ('أمان', 'أمان'), ('أخرى', 'أخرى'), ('تنزيل', 'تنزيل')], default=1, max_length=50, verbose_name='نوع الحساب')),
                ('value', models.FloatField(verbose_name='المبلغ')),
                ('isDone', models.BooleanField(blank=True, null=True, verbose_name='انتهاء السداد')),
                ('isDown', models.BooleanField(blank=True, null=True, verbose_name='سداد أم دفع')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('time', models.TimeField(default=django.utils.timezone.now, verbose_name='Time')),
                ('dateTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Time')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customerData', to='customers.mandopinfo', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'مبيعات',
                'verbose_name_plural': 'سجل المبيعات',
                'ordering': ['-dateTime'],
            },
        ),
    ]
