# Generated by Django 3.1.5 on 2021-12-22 14:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_auto_20211222_1443'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sellersApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellerrecord',
            options={'managed': True, 'verbose_name': 'مبيعات', 'verbose_name_plural': 'سجل المبيعات'},
        ),
        migrations.RemoveField(
            model_name='sellerrecord',
            name='dateTime',
        ),
        migrations.AddField(
            model_name='sellerrecord',
            name='accountant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Store.accountant+', to=settings.AUTH_USER_MODEL, verbose_name='المحاسب'),
        ),
        migrations.AddField(
            model_name='sellerrecord',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='DateTime'),
        ),
        migrations.AddField(
            model_name='sellerrecord',
            name='notes',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='الملاحظات'),
        ),
        migrations.AddField(
            model_name='sellerrecord',
            name='rest',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='المتبقى'),
        ),
        migrations.AlterField(
            model_name='sellerrecord',
            name='isDone',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='انتهاء السداد'),
        ),
        migrations.AlterField(
            model_name='sellerrecord',
            name='isDown',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='تحويل أم تنزبل'),
        ),
        migrations.AlterField(
            model_name='sellerrecord',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Store.seller+', to='customers.mandopinfo', verbose_name='المندوب'),
        ),
        migrations.AlterField(
            model_name='sellerrecord',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'أرصدة'), (2, 'تنزيل'), (3, 'تحصيل'), (4, 'شراء'), (5, 'الدفع')], null=True, verbose_name='نوع الحساب'),
        ),
    ]
