# Generated by Django 3.1.5 on 2022-02-27 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcashApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'managed': False},
        ),
    ]
