# Generated by Django 3.1.5 on 2022-02-27 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcashApp', '0002_auto_20220227_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'managed': True},
        ),
    ]
