# Generated by Django 3.1.5 on 2022-02-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcashApp', '0003_auto_20220227_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='deviceid',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
