# Generated by Django 3.1.5 on 2022-02-27 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vcashApp', '0007_simlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simlog',
            name='sim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vcashApp.sim'),
        ),
        migrations.CreateModel(
            name='TransactionsCash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=45)),
                ('value', models.FloatField()),
                ('rest', models.FloatField(blank=True, null=True)),
                ('operationno', models.CharField(blank=True, max_length=100, null=True)),
                ('messagedate', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('type', models.IntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vcashApp.device')),
                ('sim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vcashApp.sim')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Device.Account+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-datetime'],
                'managed': True,
            },
        ),
    ]
