# Generated by Django 3.1.5 on 2022-03-03 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0011_auto_20211222_1443'),
        ('vcashApp', '0008_auto_20220227_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionscash',
            name='type',
        ),
        migrations.AddField(
            model_name='transactionscash',
            name='isSend',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionscash',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TransactionsCash.MandopInfo+', to='customers.mandopinfo'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='isused',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='sim',
            name='number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sim',
            name='phone',
            field=models.CharField(blank=True, max_length=45, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transactionscash',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TransactionsCash.Account+', to=settings.AUTH_USER_MODEL),
        ),
    ]
