# Generated by Django 3.1.5 on 2022-03-03 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcashApp', '0009_auto_20220303_1327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'managed': True, 'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='sim',
            options={'managed': True, 'ordering': ['-number']},
        ),
    ]
