# Generated by Django 3.1.5 on 2022-03-10 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcashApp', '0012_auto_20220306_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='baddress',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='deviceid',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='imei',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
