# Generated by Django 3.1.5 on 2022-01-13 18:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='متاح')),
                ('day', models.DateField(blank=True, null=True, verbose_name='اليوم')),
                ('startTime', models.TimeField(blank=True, null=True, verbose_name='بداية اليوم')),
                ('endTime', models.TimeField(blank=True, null=True, verbose_name='نهاية اليوم')),
                ('duration', models.TimeField(blank=True, null=True, verbose_name='الفترة')),
                ('dateTime', models.DateTimeField(blank=True, default=datetime.datetime.today, null=True, verbose_name='Date Time')),
                ('transport', models.FloatField(blank=True, default=0, null=True, verbose_name='تكلفة المواصلات')),
                ('notes', models.TextField(blank=True, default='', null=True, verbose_name='الملاحظات')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FollowUp.user+', to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'متابعه',
                'verbose_name_plural': 'المتابعات',
                'ordering': ['dateTime'],
            },
        ),
    ]
