# Generated by Django 3.1.5 on 2021-12-30 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FollowUpApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(help_text='مطلوب إضافة الايميل', max_length=100, verbose_name='UID')),
                ('email', models.CharField(max_length=100, verbose_name='الايميل')),
                ('name', models.CharField(max_length=30, verbose_name='الإسم')),
                ('image', models.CharField(blank=True, max_length=300, null=True, verbose_name='الصورة الشخصية')),
                ('phone', models.CharField(blank=True, help_text='مطلوب إضافة رقم التليفون', max_length=11, null=True, unique=True, verbose_name='رقم التليفون')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='أخر دخول')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='مسئول عام')),
                ('is_admin', models.BooleanField(default=False, verbose_name='مدير')),
                ('is_staff', models.BooleanField(default=False, verbose_name='محاسب')),
                ('is_active', models.BooleanField(default=False, verbose_name='نشط')),
                ('type', models.IntegerField(choices=[(0, 'محاسب'), (1, 'مندوب'), (2, 'عميل'), (3, 'محصل'), (4, 'محول'), (5, 'مدير')], default=0, verbose_name='نوع الحساب')),
            ],
            options={
                'verbose_name': 'الموظف',
                'verbose_name_plural': 'الموظفين',
                'ordering': ['-last_login'],
            },
        ),
        migrations.RemoveField(
            model_name='followup',
            name='email',
        ),
        migrations.RemoveField(
            model_name='followup',
            name='name',
        ),
        migrations.RemoveField(
            model_name='followup',
            name='uid',
        ),
        migrations.AddField(
            model_name='followup',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='FollowUp.user+', to='FollowUpApp.employers', verbose_name='الموظف'),
        ),
    ]
