# Generated by Django 3.1.5 on 2022-01-05 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FollowUpApp', '0003_auto_20220102_1528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followup',
            options={'ordering': ['-datetime'], 'verbose_name': 'متابعه', 'verbose_name_plural': 'المتابعات'},
        ),
        migrations.RenameField(
            model_name='followup',
            old_name='dateTime',
            new_name='datetime',
        ),
    ]
