# Generated by Django 3.1.5 on 2022-01-05 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FollowUpApp', '0004_auto_20220105_1301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followup',
            options={'ordering': ['-dateTime'], 'verbose_name': 'متابعه', 'verbose_name_plural': 'المتابعات'},
        ),
        migrations.RenameField(
            model_name='followup',
            old_name='datetime',
            new_name='dateTime',
        ),
    ]
