# Generated by Django 3.1.5 on 2022-01-08 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FollowUpApp', '0005_auto_20220105_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followup',
            options={'ordering': ['dateTime'], 'verbose_name': 'متابعه', 'verbose_name_plural': 'المتابعات'},
        ),
    ]
