# Generated by Django 3.1.5 on 2022-02-04 19:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DataTogar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name2', models.CharField(max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Date')),
                ('time', models.TimeField(default=django.utils.timezone.now, null=True, verbose_name='Time')),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dataEltogarApp.test')),
            ],
        ),
    ]
