# Generated by Django 3.1.5 on 2022-01-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataTogar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfMandoop', models.CharField(blank=True, max_length=50, null=True, verbose_name='إسم المندوب')),
                ('activityKind', models.CharField(blank=True, max_length=50, null=True, verbose_name='إسم المندوب')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='إسم المندوب')),
                ('area', models.CharField(blank=True, max_length=50, null=True, verbose_name='إسم المندوب')),
                ('evaluate', models.CharField(blank=True, max_length=50, null=True, verbose_name='إسم المندوب')),
                ('notes', models.CharField(blank=True, max_length=50, null=True, verbose_name='إسم المندوب')),
                ('phoneNumber', models.CharField(blank=True, max_length=50, null=True, verbose_name='إسم المندوب')),
                ('shopName', models.CharField(blank=True, max_length=50, null=True, verbose_name='إسم المندوب')),
                ('ownerName', models.CharField(blank=True, max_length=50, null=True, verbose_name='إسم المندوب')),
                ('time', models.CharField(blank=True, max_length=50, null=True, verbose_name='إسم المندوب')),
                ('date', models.CharField(blank=True, max_length=50, null=True, verbose_name='إسم المندوب')),
                ('sellerLangitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='إسم المندوب')),
                ('sellerLatittude', models.CharField(blank=True, max_length=50, null=True, verbose_name='إسم المندوب')),
                ('intention', models.CharField(blank=True, max_length=50, null=True, verbose_name='إسم المندوب')),
                ('tayer', models.CharField(blank=True, max_length=50, null=True, verbose_name='إسم المندوب')),
                ('tayerFromWho', models.CharField(blank=True, max_length=50, null=True, verbose_name='إسم المندوب')),
                ('amountPayTayer', models.CharField(blank=True, max_length=50, null=True, verbose_name='إسم المندوب')),
                ('cash', models.CharField(blank=True, max_length=50, null=True, verbose_name='إسم المندوب')),
                ('intent_cash', models.CharField(blank=True, max_length=50, null=True, verbose_name='إسم المندوب')),
                ('amountPayCash', models.CharField(blank=True, max_length=50, null=True, verbose_name='إسم المندوب')),
                ('kindOfMobile', models.CharField(blank=True, max_length=50, null=True, verbose_name='إسم المندوب')),
                ('mobileNotes', models.CharField(blank=True, max_length=50, null=True, verbose_name='إسم المندوب')),
                ('mobileFromWhow', models.CharField(blank=True, max_length=50, null=True, verbose_name='إسم المندوب')),
                ('machinesOfepay', models.CharField(blank=True, max_length=50, null=True, verbose_name='إسم المندوب')),
                ('machinesOfepayIsNeedMachine', models.CharField(blank=True, max_length=50, null=True, verbose_name='إسم المندوب')),
                ('amountOfTreat', models.CharField(blank=True, max_length=50, null=True, verbose_name='إسم المندوب')),
                ('sim', models.CharField(blank=True, max_length=50, null=True, verbose_name='إسم المندوب')),
                ('cardNotes', models.CharField(blank=True, max_length=50, null=True, verbose_name='إسم المندوب')),
                ('bakar', models.CharField(blank=True, max_length=50, null=True, verbose_name='إسم المندوب')),
                ('bakar_intention', models.CharField(blank=True, max_length=50, null=True, verbose_name='إسم المندوب')),
                ('bakar_withdraw', models.CharField(blank=True, max_length=50, null=True, verbose_name='إسم المندوب')),
                ('bakarFromWho', models.CharField(blank=True, max_length=50, null=True, verbose_name='إسم المندوب')),
                ('bakarNotes', models.CharField(blank=True, max_length=50, null=True, verbose_name='إسم المندوب')),
            ],
        ),
    ]
